package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class is generated by the JSON to Java Class Generator.
 */
public class Phonenumber {
    @JsonProperty(access = JsonProperty.Access.AUTO, value = "type")
    private String type;

    @JsonProperty(access = JsonProperty.Access.AUTO, value = "number")
    private String number;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

}
