package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * This class is generated by the JSON to Java Class Generator.
 */
public class Test {
    @JsonProperty(access = JsonProperty.Access.AUTO, value = "name")
    private String name;

    @JsonProperty(access = JsonProperty.Access.AUTO, value = "birthDate")
    private String birthDate;

    @JsonProperty(access = JsonProperty.Access.AUTO, value = "isStudent")
    private Boolean isStudent;

    @JsonProperty(access = JsonProperty.Access.AUTO, value = "grades")
    private List<Integer> grades;

    @JsonProperty(access = JsonProperty.Access.AUTO, value = "address")
    private Address address;

    @JsonProperty(access = JsonProperty.Access.AUTO, value = "phoneNumbers")
    private List<Phonenumber> phoneNumbers;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBirthdate() {
        return birthDate;
    }

    public void setBirthdate(String birthDate) {
        this.birthDate = birthDate;
    }

    public Boolean getIsstudent() {
        return isStudent;
    }

    public void setIsstudent(Boolean isStudent) {
        this.isStudent = isStudent;
    }

    public List<Integer> getGrades() {
        return grades;
    }

    public void setGrades(List<Integer> grades) {
        this.grades = grades;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public List<Phonenumber> getPhonenumbers() {
        return phoneNumbers;
    }

    public void setPhonenumbers(List<Phonenumber> phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
    }

}
